In [2]:
!unzip '/content/Lab1 - Ciencia de Dados.zip'

Archive:  /content/Lab1 - Ciencia de Dados.zip
replace relatorio_exemploFulano.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [4]:
import pandas as pd

# 1.1 Load the imdb.csv file into a DataFrame
df = pd.read_csv('imdb.csv')

# 1.2 Display the first 5 rows and use .info() and .describe() to explore the dataset
display(df.head())
df.info()
display(df.describe())

# 1.3 Identify columns with missing values
print("\nColumns with missing values:")
print(df.isnull().sum()[df.isnull().sum() > 0])

,id,title,link,year,duration,rating_mpa,rating_imdb,vote,budget,gross_world_wide,...,writer,star,genre,country_origin,filming_location,production_company,language,win,nomination,oscar
0,tt0073470,Strip Nude for Your Killer,https://www.imdb.com/title/tt0073470,1975,1h 38m,Not Rated,5.6,33000.0,NaN,NaN,...,"Andrea Bianchi, Massimo Felisatti","Edwige Fenech, Nino Castelnuovo, Femi Benussi","Erotic Thriller, Giallo, Slasher Horror, Horro...",Italy,"Milan, Lombardia, Italy",FRAL Cinematografica,Italian,0,0,0
1,tt0072764,Carry on Behind,https://www.imdb.com/title/tt0072764,1975,1h 30m,Not Rated,5.6,31000.0,NaN,NaN,...,Dave Freeman,"Elke Sommer, Kenneth Williams, Bernard Bresslaw","Parody, Slapstick, Comedy",United Kingdom,"Bad Godesberg Way, Maidenhead, Berkshire, Engl...","The Rank Organisation, Peter Rogers Productions",English,0,0,0
2,tt0131526,"So Young, So Lovely, So Vicious...",https://www.imdb.com/title/tt0131526,1975,1h 30m,NaN,4.9,487.0,NaN,NaN,...,"Silvio Amadio, Roberto Natale","Gloria Guida, Dagmar Lassander, Fred Robsahm","Drama, Mystery, Thriller",Italy,"Sardinia, Italy",Domiziana Internazionale Cinematografica,Italian,0,0,0
3,tt0073335,Mahogany,https://www.imdb.com/title/tt0073335,1975,1h 49m,PG,6.1,23000.0,NaN,NaN,...,"John Byrum, Toni Amber","Diana Ross, Billy Dee Williams, Anthony Perkins","Drama, Romance",United States,Marshall Field Co Department Store 111 N Sta...,"Motown Productions, Nikor Productions, Paramou...","English, Italian",0,0,1
4,tt0073006,Foreplay,https://www.imdb.com/title/tt0073006,1975,1h 15m,R,4.0,185.0,NaN,NaN,...,"Dan Greenburg, Jack Richardson, Bruce Jay Frie...","Irwin Corey, Pat Paulsen, Deborah Loomis","Parody, Satire, Sketch Comedy, Comedy",United States,NaN,SynFrank Enterprises,English,0,0,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33600 entries, 0 to 33599
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     33600 non-null  object
 1   title                  33600 non-null  object
 2   link                   33600 non-null  object
 3   year                   33600 non-null  int64
 4   duration               33379 non-null  object
 5   rating_mpa             25624 non-null  object
 6   rating_imdb            33462 non-null  float64
 7   vote                   33462 non-null  float64
 8   budget                 11815 non-null  float64
 9   gross_world_wide       18222 non-null  float64
 10  gross_us_canada        17571 non-null  float64
 11  gross_opening_weekend  15523 non-null  float64
 12  director               33241 non-null  object
 13  writer                 32024 non-null  object
 14  star                   33127 non-null  object
 15  genre                  33218 non-null  object
 16  country_origin         33234 non-null  object
 17  filming_location       26871 non-null  object
 18  production_company     32222 non-null  object
 19  language               33109 non-null  object
 20  win                    33600 non-null  int64
 21  nomination             33600 non-null  int64
 22  oscar                  33600 non-null  int64
dtypes: float64(6), int64(4), object(13)
memory usage: 5.9+ MB

,year,rating_imdb,vote,budget,gross_world_wide,gross_us_canada,gross_opening_weekend,win,nomination,oscar
count,33600.000000,33462.000000,3.346200e+04,1.181500e+04,1.822200e+04,1.757100e+04,1.552300e+04,33600.0,33600.000000,33600.000000
mean,1992.393631,6.155158,6.637211e+04,8.454320e+07,3.814961e+07,1.808236e+07,5.110082e+06,0.0,4.850357,0.102619
std,18.957395,1.146070,6.653147e+05,2.866281e+09,1.210105e+08,4.853181e+07,1.488319e+07,0.0,17.719188,0.508687
min,1960.000000,1.100000,6.000000e+00,1.000000e+00,1.000000e+00,6.400000e+01,1.100000e+01,0.0,0.000000,0.000000
25%,1976.000000,5.500000,5.170000e+02,2.000000e+06,1.589938e+05,8.603650e+04,1.399650e+04,0.0,0.000000,0.000000
50%,1993.000000,6.300000,1.400000e+04,9.000000e+06,2.311544e+06,9.094110e+05,1.075360e+05,0.0,0.000000,0.000000
75%,2009.000000,7.000000,4.000000e+04,2.700000e+07,2.092931e+07,1.405137e+07,3.772558e+06,0.0,3.000000,0.000000
max,2024.000000,9.600000,2.600000e+07,3.000000e+11,2.923706e+09,9.366622e+08,3.571150e+08,0.0,433.000000,11.000000

Columns with missing values:
duration                   221
rating_mpa                7976
rating_imdb                138
vote                       138
budget                   21785
gross_world_wide         15378
gross_us_canada          16029
gross_opening_weekend    18077
director                   359
writer                    1576
star                       473
genre                      382
country_origin             366
filming_location          6729
production_company        1378
language                   491
dtype: int64

In [7]:
# 2.1 Convert columns to appropriate numeric types
# 'year' is already int64, 'rating_imdb' and 'vote' are float64
# 'duration' needs to be converted from string (e.g., '1h 38m') to minutes (numeric)

def convert_duration(duration_str):
    if pd.isna(duration_str):
        return None
    try:
        parts = duration_str.replace('h', ' ').replace('m', '').split()
        hours = int(parts[0]) if parts else 0
        minutes = int(parts[1]) if len(parts) > 1 else 0
        return hours * 60 + minutes
    except ValueError:
        return None # Handle cases where the format is not as expected

df['duration'] = df['duration'].apply(convert_duration)

# 2.2 Create a new column profit = gross_world_wide - budget
df['profit'] = df['gross_world_wide'] - df['budget']

# 2.3 Standardize column names (no spaces and lowercase)
df.columns = df.columns.str.replace(' ', '_').str.lower()

# Display the first few rows and info to verify the changes
display(df.head())
df.info()

,id,title,link,year,duration,rating_mpa,rating_imdb,vote,budget,gross_world_wide,...,star,genre,country_origin,filming_location,production_company,language,win,nomination,oscar,profit
0,tt0073470,Strip Nude for Your Killer,https://www.imdb.com/title/tt0073470,1975,98.0,Not Rated,5.6,33000.0,NaN,NaN,...,"Edwige Fenech, Nino Castelnuovo, Femi Benussi","Erotic Thriller, Giallo, Slasher Horror, Horro...",Italy,"Milan, Lombardia, Italy",FRAL Cinematografica,Italian,0,0,0,NaN
1,tt0072764,Carry on Behind,https://www.imdb.com/title/tt0072764,1975,90.0,Not Rated,5.6,31000.0,NaN,NaN,...,"Elke Sommer, Kenneth Williams, Bernard Bresslaw","Parody, Slapstick, Comedy",United Kingdom,"Bad Godesberg Way, Maidenhead, Berkshire, Engl...","The Rank Organisation, Peter Rogers Productions",English,0,0,0,NaN
2,tt0131526,"So Young, So Lovely, So Vicious...",https://www.imdb.com/title/tt0131526,1975,90.0,NaN,4.9,487.0,NaN,NaN,...,"Gloria Guida, Dagmar Lassander, Fred Robsahm","Drama, Mystery, Thriller",Italy,"Sardinia, Italy",Domiziana Internazionale Cinematografica,Italian,0,0,0,NaN
3,tt0073335,Mahogany,https://www.imdb.com/title/tt0073335,1975,109.0,PG,6.1,23000.0,NaN,NaN,...,"Diana Ross, Billy Dee Williams, Anthony Perkins","Drama, Romance",United States,Marshall Field Co Department Store 111 N Sta...,"Motown Productions, Nikor Productions, Paramou...","English, Italian",0,0,1,NaN
4,tt0073006,Foreplay,https://www.imdb.com/title/tt0073006,1975,75.0,R,4.0,185.0,NaN,NaN,...,"Irwin Corey, Pat Paulsen, Deborah Loomis","Parody, Satire, Sketch Comedy, Comedy",United States,NaN,SynFrank Enterprises,English,0,0,0,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33600 entries, 0 to 33599
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     33600 non-null  object
 1   title                  33600 non-null  object
 2   link                   33600 non-null  object
 3   year                   33600 non-null  int64
 4   duration               33372 non-null  float64
 5   rating_mpa             25624 non-null  object
 6   rating_imdb            33462 non-null  float64
 7   vote                   33462 non-null  float64
 8   budget                 11815 non-null  float64
 9   gross_world_wide       18222 non-null  float64
 10  gross_us_canada        17571 non-null  float64
 11  gross_opening_weekend  15523 non-null  float64
 12  director               33241 non-null  object
 13  writer                 32024 non-null  object
 14  star                   33127 non-null  object
 15  genre                  33218 non-null  object
 16  country_origin         33234 non-null  object
 17  filming_location       26871 non-null  object
 18  production_company     32222 non-null  object
 19  language               33109 non-null  object
 20  win                    33600 non-null  int64
 21  nomination             33600 non-null  int64
 22  oscar                  33600 non-null  int64
 23  profit                 9406 non-null   float64
dtypes: float64(8), int64(4), object(12)
memory usage: 6.2+ MB

In [8]:
# 3.1 List the top 5 movies with the highest IMDb rating
print("Top 5 movies with the highest IMDb rating:")
display(df.nlargest(5, 'rating_imdb')[['title', 'rating_imdb']])

# 3.2 Calculate the average duration per decade
df['decade'] = (df['year'] // 10) * 10
average_duration_by_decade = df.groupby('decade')['duration'].mean().reset_index()
print("\nAverage duration per decade:")
display(average_duration_by_decade)

# 3.3 Find the director with the highest average IMDb rating (minimum 3 movies)
director_ratings = df.groupby('director')['rating_imdb'].agg(['mean', 'count']).reset_index()
eligible_directors = director_ratings[director_ratings['count'] >= 3]
top_director = eligible_directors.nlargest(1, 'mean')
print("\nDirector with the highest average IMDb rating (minimum 3 movies):")
display(top_director)

# 3.4 Show the most recurrent genre in the dataset
# Assuming genres are separated by commas and we want the most frequent individual genre
genres = df['genre'].str.split(', ').explode()
most_frequent_genre = genres.mode()[0]
print(f"\nMost recurrent genre in the dataset: {most_frequent_genre}")

Top 5 movies with the highest IMDb rating:

                                                title  rating_imdb
11166                         Day by Day: The Dynasty          9.6
20986                                Love Goes Public          9.6
12225                                   Water Brother          9.5
14532  SEVENTEEN TOUR 'FOLLOW' to JAPAN: LIVE VIEWING          9.5
11363                                Steeper & Deeper          9.4

Average duration per decade:

   decade    duration
0    1960  134.573593
1    1970  114.076493
2    1980  121.803039
3    1990  128.049316
4    2000  111.354923
5    2010  111.207588
6    2020  118.371116

Director with the highest average IMDb rating (minimum 3 movies):

       director      mean  count
6371  Jim Brown  8.633333      3

Most recurrent genre in the dataset: Drama

In [15]:
# 4.1 Load the oscars.csv file into another DataFrame
# It seems there is a parsing issue with the oscars.csv file.
# Let's try reading it with a different delimiter, like a semicolon, as it's common in some datasets.
try:
    oscars_df = pd.read_csv('oscars.csv', sep='\t')
except ParserError:
    print("Parsing with tab failed. Trying another delimiter or inspecting the file.")
    # If semicolon fails, you might need to inspect the file manually
    # or try other common delimiters like tab ('\t') or a fixed width parser
    # For now, we'll assume semicolon works based on the error message hinting at multiple fields
    pass


# Print column names to identify the correct merge key
print("Columns in df:", df.columns)
print("Columns in oscars_df:", oscars_df.columns)

# 4.2 Realize the merge between the main DataFrame and the oscars DataFrame
# Use 'title' from df and 'Film' from oscars_df for merging
merged_df = pd.merge(df, oscars_df, left_on='title', right_on='Film', how='left')

# 4.3 Considering only the films that won the BEST PICTURE category, identify the director with the most awards in this category.
best_picture_winners = merged_df[(merged_df['Category'] == 'BEST PICTURE') & (merged_df['Winner'] == True)]

if not best_picture_winners.empty:
    director_best_picture_wins = best_picture_winners['director'].value_counts().reset_index()
    director_best_picture_wins.columns = ['director', 'best_picture_wins']
    top_director_best_picture = director_best_picture_wins.nlargest(1, 'best_picture_wins')

    print("\nDirector with the most BEST PICTURE wins:")
    display(top_director_best_picture)
else:
    print("\nNo BEST PICTURE winners found in the merged dataset.")

Columns in df: Index(['id', 'title', 'link', 'year', 'duration', 'rating_mpa', 'rating_imdb',
       'vote', 'budget', 'gross_world_wide', 'gross_us_canada',
       'gross_opening_weekend', 'director', 'writer', 'star', 'genre',
       'country_origin', 'filming_location', 'production_company', 'language',
       'win', 'nomination', 'oscar', 'profit', 'decade'],
      dtype='object')
Columns in oscars_df: Index(['Ceremony', 'Year', 'Class', 'CanonicalCategory', 'Category', 'Film',
       'FilmId', 'Name', 'Nominees', 'NomineeIds', 'Winner', 'Detail', 'Note',
       'Citation'],
      dtype='object')

Director with the most BEST PICTURE wins:

         director  best_picture_wins
0  Clint Eastwood                  2

In [20]:
# 5.1 Create a pivot_table showing the average rating_imdb by country and decade
pivot_table_rating = df.pivot_table(values='rating_imdb', index='country_origin', columns='decade', aggfunc='mean')
print("Average IMDb rating by country and decade:")
display(pivot_table_rating)

# 5.2 Use melt to reorganize gross columns into long format
gross_columns = ['gross_world_wide', 'gross_us_canada', 'gross_opening_weekend']
melted_gross = df.melt(id_vars=['id', 'title'], value_vars=gross_columns, var_name='gross_type', value_name='gross_amount')
print("\nMelted gross columns:")
display(melted_gross.head())

Average IMDb rating by country and decade:

decade,1960,1970,1980,1990,2000,2010,2020
country_origin,,,,,,,
"Afghanistan, Ireland, Japan, Netherlands, Iran",NaN,NaN,NaN,NaN,7.3,NaN,NaN
Algeria,NaN,7.3,NaN,NaN,NaN,NaN,NaN
"Algeria, France",NaN,NaN,NaN,NaN,5.8,NaN,NaN
"Algeria, France, Morocco, Belgium",NaN,NaN,NaN,NaN,7.0,NaN,NaN
"Angola, France",NaN,7.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
"Yugoslavia, Italy, West Germany, United States, France",7.00,NaN,NaN,NaN,NaN,NaN,NaN
"Yugoslavia, United Kingdom",7.90,NaN,7.7,4.8,NaN,NaN,NaN
"Yugoslavia, United States",5.35,7.6,5.7,NaN,NaN,NaN,NaN
"Yugoslavia, United States, Liechtenstein",NaN,5.5,NaN,NaN,NaN,NaN,NaN
"Yugoslavia, West Germany",NaN,6.5,7.6,NaN,NaN,NaN,NaN

Melted gross columns:

,id,title,gross_type,gross_amount
0,tt0073470,Strip Nude for Your Killer,gross_world_wide,NaN
1,tt0072764,Carry on Behind,gross_world_wide,NaN
2,tt0131526,"So Young, So Lovely, So Vicious...",gross_world_wide,NaN
3,tt0073335,Mahogany,gross_world_wide,NaN
4,tt0073006,Foreplay,gross_world_wide,NaN

In [21]:
# 6.1 Export the pivot table to CSV
pivot_table_rating.to_csv(
    'rating_pivot_pais_decada.csv',
    index=False,
    encoding='utf-8',
    sep=',',
    na_rep='' # Represent NaN as empty string
)

print("Pivot table exported to rating_pivot_pais_decada.csv")

Pivot table exported to rating_pivot_pais_decada.csv